[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "zlib"]

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[crons]]
schedule = "0 9 * * *"
command  = "python generate_pronos.py"

[[crons]]
schedule = "0 11 * * *"
command  = "python -c 'import asyncio; from api.check_results import update_results; asyncio.run(update_results())'"
