[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "zlib", "gcc", "postgresql"]

[build.nixpacksPlan.phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[deploy]
startCommand = "python3 bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[crons]]
schedule = "0 9 * * *"
command = "python3 generate_pronos.py"

[[crons]]
schedule = "0 11 * * *"
command = "python3 -c 'import asyncio; from api.check_results import update_results; asyncio.run(update_results())'"
